version: "3"
services:
  traefik:
    image: traefik:v2.8
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
    ports:
      - 80:80
      - 8080:8080
    networks:
      - big-mama
    volumes:
      - ${APP_DIR}/traefik:/etc/traefik
      - ${DOCKER_SOCK}:${DOCKER_SOCK}:ro
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    ports:
      - 9000:9000
    networks:
      - big-mama
    volumes:
      - ${APP_DIR}/portainer:/data
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCK}:${DOCKER_SOCK}:ro
    restart: unless-stopped

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3000:3000
    networks:
      - big-mama
    volumes:
      - ${APP_DIR}/homepage:/app/config
      - ${DOCKER_SOCK}:${DOCKER_SOCK}
    restart: "unless-stopped"

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3030:80
    networks:
      - big-mama
    volumes:
      - ${APP_DIR}/filebrowser:/srv/app-data
      - ${APP_DIR}/filebrowser/data/db:/database
      - ${APP_DIR}/filebrowser/data/config:/config
      - ${MEDIA_DIR}/:/srv/media
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack:22.07.3
    container_name: bookstack
    depends_on:
      - bookstack-db
    environment:
      - APP_URL=http://192.168.0.4:3010
      - DB_HOST=bookstack-db
      - DB_USERNAME=user
      - DB_PASSWORD=123456789
      - DB_DATABASE=bookstackapp
    ports:
      - 3010:80
    networks:
      - big-mama
    volumes:
      - ${APP_DIR}/bookstack:/config
    restart: unless-stopped

  bookstack-db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack-db
    environment:
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456789
    networks:
      - big-mama
    volumes:
      - ${APP_DIR}/bookstack/db:/config
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: ${PUID}:${PGID}
    ports:
      - 8096:8096
    networks:
      - big-mama
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=http
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.localhost`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.docker.network=big-mama
    volumes:
      - ${APP_DIR}/jellyfin/config:/config
      - ${APP_DIR}/jellyfin/cache:/cache
      - ${MEDIA_DIR}:/media
      - ${DOCKER_SOCK}:${DOCKER_SOCK}
    restart: unless-stopped

 
networks:
  big-mama:
    name: big-mama
    driver: bridge