# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Applications:
    - Filebrowser:
        icon: filebrowser.png
        href: http://192.168.0.4:3030
        description: Filebrowser instance.
        container: filebrowser
    - LibReddit:
        icon: libreddit.png
        href: http://192.168.0.4:3050
        description: Open source frontend for reddit.com.
        container: libreddit

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.0.4:8096   
        description: Jellyfin media streaming instance.
        container: jellyfin
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.0.4:3070
        description: Sonarr is a RSS feed monitor.
        container: sonarr
    - Radarr:
        icon: radarr.png
        href: http://192.168.0.4:3080
        description: Radarr is a TV show monitor.
        container: radarr

- Tools:
    - Portainer:
        icon: portainer.png
        href: http://192.168.0.4:9000
        description: Portainer manages Docker / Kubernetes.
        container: portainer
    - Traefik:
        icon: traefik.png
        href: http://192.168.0.4:8080
        description: Traefik Dashboard instance.
        container: traefik
    - Grafana:
        icon: grafana.png
        href: http://192.168.0.4:3090
        description: Grafana monitoring dashboard instance.
        container: grafana
    - Pihole:
        icon:
        href: http://192.168.0.4:4010
        description: Pihole instance.
        container: pihole
