# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Applications:
    - Jellyfin:
        icon: https://features.jellyfin.org/images/logos/a7Lx9nYDzWuDR94Az8Yum7neWMvNMndkm9qr4QVtmjaMrOHDLisS5K7LJctTRzK9-icon-transparent.png?size=100
        href: http://192.168.0.4:8096   
        description: Jellyfin media streaming instance.
        server: my-docker
        container: jellyfin
    - Bookstack:
        icon: https://raw.githubusercontent.com/BookStackApp/BookStack/development/public/favicon.ico
        href: http://192.168.0.4:3010
        description: Bookstack wikipedia instance.
        container: bookstack
    - Filebrowser:
        icon: https://raw.githubusercontent.com/filebrowser/filebrowser/c1e6d5869acf32cda22fa7dd532ebb6130061b7b/frontend/public/img/logo.svg
        href: http://192.168.0.4:3030
        description: Filebrowser instance.
        container: filebrowser

- Tools:
    - Portainer:
        icon: https://cdn.worldvectorlogo.com/logos/portainer.svg
        href: http://192.168.0.4:9000
        description: Portainer manages Docker / Kubernetes.
        container: portainer
    